### ISSUE TITLE
chat application cannot start

### ISSUE THREAD

**Issue by htekgulds** [exoplatform/chat-application#84]
Hello,
I updated exo from 4.2.1 to 4.3.0 and also updated chat to 1.2.0 but it gives me the following error at startup and halts exo startup as well (chatServer is inside platform.ear):

``` log
09:45:38,139 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/chatServer]] (ServerService Thread Pool -- 57) JBWEB000287: Exception sending context initialized event to listener instance of class org.exoplatform.chat.listener.MigrateServiceListener: java.lang.NullPointerException
        at com.mongodb.DBApiLayer.getCollectionNames(DBApiLayer.java:153) [mongo-java-driver-2.14.0.jar:]
        at com.mongodb.DB.collectionExists(DB.java:524) [mongo-java-driver-2.14.0.jar:]
        at org.exoplatform.chat.services.mongodb.MongoBootstrap.initCollection(MongoBootstrap.java:158) [server-1.2.0.jar:1.2.0]
        at org.exoplatform.chat.services.mongodb.MongoBootstrap.initCollection(MongoBootstrap.java:153) [server-1.2.0.jar:1.2.0]
        at org.exoplatform.chat.services.mongodb.MongoBootstrap.getDB(MongoBootstrap.java:126) [server-1.2.0.jar:1.2.0]
        at org.exoplatform.chat.services.mongodb.MongoBootstrap.getDB(MongoBootstrap.java:110) [server-1.2.0.jar:1.2.0]
        at org.exoplatform.chat.services.MigrateService.<init>(MigrateService.java:22) [server-1.2.0.jar:1.2.0]
        at org.exoplatform.chat.listener.MigrateServiceListener.contextInitialized(MigrateServiceListener.java:19) [server-1.2.0.jar:1.2.0]
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3339) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:3777) [jbossweb-7.2.2.Final-redhat-1.jar:7.2.2.Final-redhat-1]
        at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:156) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
        at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:60) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
        at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:93) [jboss-as-web-7.3.0.Final-redhat-14.jar:7.3.0.Final-redhat-14]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_74]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_74]
        at org.jboss.threads.JBossThread.run(JBossThread.java:122)

09:45:38,145 INFO  [GuiceManager] (ServerService Thread Pool -- 57) INITIALIZING GUICE

```

**Comment by mgamboa** [comment]
i got this when i try to install chat plug-in for the first time
2016-10-16 21:27:15,900 | ERROR | Exception sending context initialized event to listener instance of class org.exoplatform.chat.listener.MigrateServiceListener [o.a.c.c.C.[.[localhost].[/chatServer]<localhost-startStop-1>]
java.lang.UnsupportedOperationException: null
        at java.util.Collections$UnmodifiableCollection.clear(Collections.java:1074) ~[na:1.8.0_102]
        at org.exoplatform.chat.services.mongodb.MongoBootstrap.getDB(MongoBootstrap.java:126) ~[server-1.3.0.jar:1.3.0]
        at org.exoplatform.chat.services.mongodb.MongoBootstrap.getDB(MongoBootstrap.java:112) ~[server-1.3.0.jar:1.3.0]
        at org.exoplatform.chat.services.MigrateService.<init>(MigrateService.java:22) ~[server-1.3.0.jar:1.3.0]
        at org.exoplatform.chat.listener.MigrateServiceListener.contextInitialized(MigrateServiceListener.java:19) ~[server-1.3.0.jar:1.3.0]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5099) [catalina.jar:7.0.70]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5615) [catalina.jar:7.0.70]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [catalina.jar:7.0.70]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899) [catalina.jar:7.0.70]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875) [catalina.jar:7.0.70]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.70]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092) [catalina.jar:7.0.70]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984) [catalina.jar:7.0.70]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_102]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]

**Comment by mgamboa** [comment]
ERROR | Exception sending context initialized event to listener instance of class org.exoplatform.chat.listener.MigrateServiceListener [o.a.c.c.C.[.[localhost].[/chatServer]<localhost-startStop-1>]
java.lang.UnsupportedOperationException: null
        at java.util.Collections$UnmodifiableCollection.clear(Collections.java:1074) ~[na:1.8.0_111]
        at org.exoplatform.chat.services.mongodb.MongoBootstrap.getDB(MongoBootstrap.java:126) ~[server-1.3.0.jar:1.3.0]
        at org.exoplatform.chat.services.mongodb.MongoBootstrap.getDB(MongoBootstrap.java:112) ~[server-1.3.0.jar:1.3.0]
        at org.exoplatform.chat.services.MigrateService.<init>(MigrateService.java:22) ~[server-1.3.0.jar:1.3.0]
        at org.exoplatform.chat.listener.MigrateServiceListener.contextInitialized(MigrateServiceListener.java:19) ~[server-1.3.0.jar:1.3.0]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5099) [catalina.jar:7.0.70]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5615) [catalina.jar:7.0.70]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [catalina.jar:7.0.70]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899) [catalina.jar:7.0.70]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875) [catalina.jar:7.0.70]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.70]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092) [catalina.jar:7.0.70]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984) [catalina.jar:7.0.70]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
2016-10-22 01:04:15,591 | ERROR | MongoDB Indexes couldn't be created during startup. Chat Extension may be unstable! [SchedulerService<localhost-startStop-1>]
2016-10-22 01:04:15,591 | ERROR | One or more listeners failed to start. Full details will be found in the appropriate container log file [org.apache.catalina.core.StandardContext<localhost-startStop-1>]
2016-10-22 01:04:15,592 | ERROR | Context [/chatServer] startup failed due to previous errors [org.apache.catalina.core.StandardContext<localhost-startStop-1>]
2016-10-22 01:04:15,594 | INFO  | CLOSING SCHEDULER [SchedulerManager<localhost-startStop-1>]
2016-10-22 01:04:15,594 | INFO  | Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutting down. [org.quartz.core.QuartzScheduler<localhost-startStop-1>]
2016-10-22 01:04:15,594 | INFO  | Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED paused. [org.quartz.core.QuartzScheduler<localhost-startStop-1>]
2016-10-22 01:04:15,594 | INFO  | Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED shutdown complete. [org.quartz.core.QuartzScheduler<localhost-startStop-1>]
2016-10-22 01:04:15,594 | INFO  | CLOSING MONGODB [ConnectionManager<localhost-startStop-1>]
2016-10-22 01:04:15,596 | INFO  | CLOSING GUICE [GuiceManager<localhost-startStop-1>]
2016-10-22 01:04:15,605 | ERROR | The web application [/chatServer] appears to have started a thread named [cluster-ClusterId{value='580a9eef330e7e0f0f300492', description='null'}-192.168.178.43:27017] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,605 | ERROR | The web application [/chatServer] appears to have started a thread named [pool-2-thread-1] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,606 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-1] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,606 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-2] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,606 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-3] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,607 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-4] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,607 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-5] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,607 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-6] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,608 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-7] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,618 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-8] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,619 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-9] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,620 | ERROR | The web application [/chatServer] appears to have started a thread named [DefaultQuartzScheduler_Worker-10] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
2016-10-22 01:04:15,621 | ERROR | The web application [/chatServer] appears to have started a thread named [cluster-ClusterId{value='580a9eef330e7e0f0f300493', description='null'}-192.168.178.43:27017] but has failed to stop it. This is very likely to create a memory leak. [o.a.c.loader.WebappClassLoaderBase<localhost-startStop-1>]
